trigger:
- none
//test
pool:
  vmImage: ubuntu-latest

stages:
- stage:
  jobs:
  - job: BuildMaven
    steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: false
          javaHomeOption: 'JDKVersion'
          goals: package

      - task: CopyFiles@2
        inputs:
          SourceFolder: $(Build.SourcesDirectory)/target
          Contents: '*SNAPSHOT.jar'
          TargetFolder: $(Build.ArtifactStagingDirectory)      
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
      
  - job: ImageBuild
    dependsOn: BuildMaven
    steps:
    - task: Docker@2
      displayName: DockerCLi
      inputs:
        command: login
        containerRegistry: acr_svc
    
    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: drop
        downloadPath: $(Build.SourcesDirectory)
    
    - task: Docker@2
      displayName: DockerBuild
      inputs:
        command: build
        repository: app/dev/snapshot
        tags: 
          v1.0.1
        arguments: --build-arg jar=*.war
    
    - task: Docker@2
      displayName: DockerPublish
      inputs: 
        command: push
        repository: app/dev/snapshot
        tags:
          v1.0.1